kinerity_bestanswer_main_controller:
    pattern: /answer/{action}
    defaults: { _controller: kinerity.bestanswer.main.controller:change_post_status }
    requirements:
        action: mark_answer|unmark_answer
